const T={id:{app:"Catatan Keuangan",hello:"Semua tersimpan di perangkat ✨",balance:"Saldo",offline:"100% Offline",income:"Pemasukan",expense:"Pengeluaran",summary:"Ringkasan Bulan Ini",budget:"Budget Bulanan",used:"Terpakai",chart:"Grafik Pengeluaran",saving:"Target Tabungan",calendar:"Kalender Transaksi",activity:"Transaksi Terbaru",clear:"Hapus",empty:"Belum ada transaksi",home:"Beranda",add:"Tambah",settings:"Pengaturan",amount:"Jumlah",category:"Kategori",date:"Tanggal",note:"Catatan",save:"Simpan",language:"Bahasa",currency:"Mata Uang",currencyTip:"Tidak ada konversi kurs. Semua transaksi menggunakan satu mata uang yang dipilih.",backup:"Data & Backup",export:"Backup Data",import:"Pulihkan Data",backupNote:"Backup tersimpan sebagai file di perangkatmu. Tidak menggunakan internet.",ic:["Gaji","Bonus","Bisnis","Hadiah","Lainnya"],ec:["Makanan","Transportasi","Belanja","Tagihan","Hiburan","Kesehatan","Lainnya"]},zh:{app:"私人記帳",hello:"所有資料都儲存在裝置中 ✨",balance:"餘額",offline:"100% 離線",income:"收入",expense:"支出",summary:"本月摘要",budget:"每月預算",used:"已使用",chart:"支出圖表",saving:"儲蓄目標",calendar:"交易日曆",activity:"最近交易",clear:"刪除",empty:"目前沒有交易",home:"首頁",add:"新增",settings:"設定",amount:"金額",category:"分類",date:"日期",note:"備註",save:"儲存",language:"語言",currency:"貨幣",currencyTip:"不進行匯率轉換。所有交易都使用您選擇的單一貨幣。",backup:"資料與備份",export:"備份資料",import:"還原資料",backupNote:"備份為裝置上的檔案，不需要網路。",ic:["薪資","獎金","生意","禮物","其他"],ec:["飲食","交通","購物","帳單","娛樂","醫療","其他"]}};
const C={IDR:{s:"Rp",loc:"id-ID"},MYR:{s:"RM",loc:"en-MY"},TWD:{s:"NT$",loc:"zh-TW"}};
let S=JSON.parse(localStorage.getItem("financeOfflineV3")||"null")||{lang:"id",cur:"IDR",tx:[],budget:0,goal:0,goalName:"Tabungan"},type="in";
const $=s=>document.querySelector(s), tr=k=>T[S.lang][k], today=()=>new Date().toISOString().slice(0,10);
function money(n){return C[S.cur].s+" "+new Intl.NumberFormat(C[S.cur].loc,{maximumFractionDigits:2}).format(n)}
function save(){localStorage.setItem("financeOfflineV3",JSON.stringify(S))}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function render(){document.querySelectorAll("[data-i]").forEach(e=>e.textContent=tr(e.dataset.i));$("#badge").textContent=S.cur;$("#lang").value=S.lang;$("#cur").value=S.cur;let now=new Date(), y=now.getFullYear(),m=now.getMonth(), arr=S.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}),a=arr.filter(x=>x.type=="in").reduce((s,x)=>s+x.amount,0),b=arr.filter(x=>x.type=="out").reduce((s,x)=>s+x.amount,0),allin=S.tx.filter(x=>x.type=="in").reduce((s,x)=>s+x.amount,0),allout=S.tx.filter(x=>x.type=="out").reduce((s,x)=>s+x.amount,0);$("#balance").textContent=money(allin-allout);$("#inc").textContent=money(a);$("#exp").textContent=money(b);$("#month").textContent=now.toLocaleDateString(S.lang=="zh"?"zh-TW":"id-ID",{month:"long",year:"numeric"});$("#budgetText").textContent=money(b)+" / "+money(S.budget);$("#bar").style.width=S.budget?Math.min(100,b/S.budget*100)+"%":"0%";$("#goalName").textContent=S.goalName;$("#goalText").textContent=money(allin)+" / "+money(S.goal);$("#goalbar").style.width=S.goal?Math.min(100,allin/S.goal*100)+"%":"0%";drawChart(arr);drawCal(y,m);drawList()}
function drawChart(arr){let ds=Array(7).fill(0);arr.filter(x=>x.type=="out").forEach(x=>{let d=new Date(x.date).getDate();ds[Math.min(6,Math.floor((d-1)/5))]+=x.amount});let max=Math.max(...ds,1);$("#bars").innerHTML=ds.map(v=>`<i class="baritem" style="height:${Math.max(4,v/max*100)}%"></i>`).join("")}
function drawCal(y,m){let first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),names=S.lang=="zh"?["日","一","二","三","四","五","六"]:["M","S","T","W","T","F","S"];let out=names.map(x=>`<div class="day head">${x}</div>`).join("");let has=new Set(S.tx.filter(x=>{let d=new Date(x.date);return d.getFullYear()==y&&d.getMonth()==m}).map(x=>new Date(x.date).getDate()));for(let i=0;i<first;i++)out+="<div></div>";for(let d=1;d<=days;d++){let cls="day "+(has.has(d)?"has ":"")+(d==new Date().getDate()?"today":"");out+=`<div class="${cls}">${d}</div>`}$("#calendar").innerHTML=out;$("#calTitle").textContent=new Date(y,m).toLocaleDateString(S.lang=="zh"?"zh-TW":"id-ID",{month:"long"})}
function drawList(){$("#empty").style.display=S.tx.length?"none":"block";$("#list").innerHTML=[...S.tx].reverse().slice(0,12).map(x=>{let d=new Date(x.date).toLocaleDateString(S.lang=="zh"?"zh-TW":"id-ID",{day:"2-digit",month:"short",year:"numeric"});return `<div class="tx"><div class="txicon">${x.type=="in"?"💰":"🛍️"}</div><div class="txmain"><div class="txcat">${esc(x.cat)}</div><div class="txdate">${d}${x.note?" · "+esc(x.note):""}</div></div><div class="txamt ${x.type=="in"?"plus":"minus"}">${x.type=="in"?"+":"−"} ${money(x.amount)}</div></div>`}).join("")}
function openAdd(k){type=k;$("#modalTitle").textContent=tr(k=="in"?"income":"expense");$("#cat").innerHTML=(k=="in"?T[S.lang].ic:T[S.lang].ec).map(x=>`<option>${x}</option>`).join("");$("#amount").value="";$("#date").value=today();$("#note").value="";$("#modal").classList.remove("hidden")}
$("#income").onclick=()=>openAdd("in");$("#expense").onclick=()=>openAdd("out");$("#add").onclick=()=>openAdd("out");$("#close").onclick=()=>$("#modal").classList.add("hidden");
$("#settings").onclick=()=>$("#setmodal").classList.remove("hidden");$("#navsettings").onclick=()=>$("#setmodal").classList.remove("hidden");$("#closes").onclick=()=>$("#setmodal").classList.add("hidden");
$("#lang").onchange=e=>{S.lang=e.target.value;save();render()};$("#cur").onchange=e=>{let old=S.cur;S.cur=e.target.value;if(S.tx.length&&!confirm(S.lang=="id"?"Mata uang diganti. Nominal transaksi lama tidak dikonversi. Lanjut?":"貨幣已更改。舊交易金額不會轉換。繼續嗎？")){S.cur=old;$("#cur").value=old;return}save();render()};
$("#form").onsubmit=e=>{e.preventDefault();let n=Number($("#amount").value);if(!n)return;S.tx.push({type,amount:n,cat:$("#cat").value,note:$("#note").value.trim(),date:$("#date").value+"T12:00:00"});save();$("#modal").classList.add("hidden");render()};
function simple(kind){$("#simple").classList.remove("hidden");$("#simpleName").style.display=kind=="goal"?"block":"none";$("#simpleTitle").textContent=kind=="goal"?tr("saving"):tr("budget");$("#simpleLabel").textContent=kind=="goal"?"Target "+C[S.cur].s:"Budget "+C[S.cur].s;$("#simpleInput").value=kind=="goal"?S.goal:S.budget;$("#simpleName").value=S.goalName;$("#simpleSave").onclick=()=>{if(kind=="goal"){S.goal=Number($("#simpleInput").value);S.goalName=$("#simpleName").value||"Tabungan"}else S.budget=Number($("#simpleInput").value);save();$("#simple").classList.add("hidden");render()}}
$("#budgetBtn").onclick=()=>simple("budget");$("#goalBtn").onclick=()=>simple("goal");$("#simpleClose").onclick=()=>$("#simple").classList.add("hidden");
$("#clear").onclick=()=>{if(S.tx.length&&confirm(S.lang=="id"?"Hapus semua transaksi?":"刪除全部交易？")){S.tx=[];save();render()}};
$("#export").onclick=()=>{let blob=new Blob([JSON.stringify(S,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="backup-keuangan.json";a.click();URL.revokeObjectURL(a.href)};
$("#import").onclick=()=>$("#file").click();$("#file").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.tx)throw 0;S=x;save();render();alert(S.lang=="id"?"Data berhasil dipulihkan.":"資料還原成功。")}catch{alert("File backup tidak valid.")}};r.readAsText(f)};
render();